# Generated by Django 4.1.5 on 2023-01-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, choices=[('Bronze', 'Globalnet Bronze'), ('Silver', 'Globalnet Silver'), ('Gold', 'Globalnet Gold')], max_length=100, null=True)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_mail', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('plans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.subscription')),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
    ]
